version: '3'
services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: infile-app
    restart: always
    ports:
      - "3000:3000"
  mysql:
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/my.cnf:/etc/mysql/my.cnf"